//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHLogViewer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Commands {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Commands"]));
            }
            set {
                this["Commands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Server\\wildfly-8.1.0.Final2\\bin\\jboss-cli.bat")]
        public string JBossTerminate {
            get {
                return ((string)(this["JBossTerminate"]));
            }
            set {
                this["JBossTerminate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--connect command=:shutdown")]
        public string JBossTerminateArguments {
            get {
                return ((string)(this["JBossTerminateArguments"]));
            }
            set {
                this["JBossTerminateArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SSHLogViewer.ConnectionInfoCollection Connections {
            get {
                return ((global::SSHLogViewer.ConnectionInfoCollection)(this["Connections"]));
            }
            set {
                this["Connections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--login -i -c /D/Server/wildfly-8.1.0.Final2/bin/standalone.sh")]
        public string JBossCommandArguments {
            get {
                return ((string)(this["JBossCommandArguments"]));
            }
            set {
                this["JBossCommandArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Git\\bin\\sh.exe")]
        public string JBossCommand {
            get {
                return ((string)(this["JBossCommand"]));
            }
            set {
                this["JBossCommand"] = value;
            }
        }
    }
}
